//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuikAid_T.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class phoneTable
    {

        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "Please enter Phone Number to submit your request")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Please enter 10 digits Phone number (No special symbols)")]
        public int phoneNumber { get; set; }

        [DisplayName("Please enter Client ID")]
        public int clientID { get; set; }
    
        public virtual clientTable clientTable { get; set; }
    }
}
